name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release-*

permissions:
  contents: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.spec.name }}
    runs-on: ${{ matrix.spec.runner }}
    container:
      image: ${{ matrix.spec.builder }}
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      VCPKG_FEATURE_FLAGS: dependencygraph
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        spec:
          - { name: 'Linux x86_64', runner: 'ubuntu-latest', target: 'linux-x64', builder: 'openziti/ziti-builder:v2', test: 'true' }
          - { name: 'Linux ARM', runner: 'ubuntu-latest', target: 'linux-arm', builder: 'openziti/ziti-builder:v2' }
          - { name: 'Linux ARM64', runner: 'ubuntu-latest', target: 'linux-arm64', builder: 'openziti/ziti-builder:v2' }
          - { name: 'MacOS x86_64', runner: 'macOS-13', target: 'macOS-x64', test: 'true' }
          - { name: 'MacOS arm64', runner: 'macOS-14', target: 'macOS-arm64', test: 'true' }
          - { name: 'Windows x86_64', runner: 'windows-2022', target: 'windows-x64', test: 'true' }
          - { name: 'Windows x86', runner: 'windows-2022', target: 'windows-x86', test: 'true' }
          - { name: 'Windows ARM64', runner: 'windows-2022', target: 'windows-arm64' }
    steps:
      - name: Add msbuild to PATH
        if: startsWith(matrix.spec.runner, 'windows')
        uses: microsoft/setup-msbuild@v2

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: run build for ${{ matrix.spec.target }}
        uses: ./.github/actions/build
        with:
          target: ${{ matrix.spec.target }}
          test: ${{ matrix.spec.test }}
          test_id: ${{ secrets.ZITI_TEST_IDENTITY }}

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ziti-prox-c-${{ matrix.spec.target }}
          path: ./build/programs/ziti-prox-c/**/ziti-prox-c*.zip

      - name: upload SDK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ziti-sdk-${{ matrix.spec.target }}
          path: ./build/package/ziti-sdk-*

  publish:
    name: Publish Nightly Artifacts
    # if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          path: ./artifacts
          pattern: ziti-sdk-*
          merge-multiple: 'false'

      - run: ls -lR ./artifacts
      - uses: pyTooling/Actions/releaser@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          rm: true
          files: |
            ./artifacts/*/*.zip